scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/professor_cat/char_cfg.yaml
      motion_cfg: examples/config/motion/yehors_dance.yaml
      retarget_cfg: examples/config/retarget/mixamo_fff_rokoko.yaml
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.gif
